### ISSUE TITLE
Add option to connections to change id or remove itself

### ISSUE THREAD

**Issue by chren-de-large** [chren-de-large/troubleshooter-editor#2]
1. Let user to change ID of connected node via dropdown in top right corner

2. Let user to Add new node and then remove connection and leave unconnected node there

<img width="351" alt="screen shot 2018-10-24 at 1 11 46 pm" src="https://user-images.githubusercontent.com/1671375/47426793-8d416080-d78e-11e8-9340-74943d3bf5bc.png">

**Comment by keip** [comment]
done 7795d6be2b

**Comment by chren-de-large** [comment]
nice
