### ISSUE TITLE
Add fulltext search

### ISSUE THREAD

**Issue by chren-de-large** [chren-de-large/troubleshooter-editor#8]
Would be nice to implement some very simple fulltext filter that will highlight nodes that contains specific text - it would make job for filler more easy when they will try to edit someting in already established file.

probably on the left side next to the burger nav

**Comment by chren-de-large** [comment]
![oct-30-2018 11-28-53](https://user-images.githubusercontent.com/1671375/47712171-54463780-dc37-11e8-97b7-6ade6ddf887c.gif)

Clicking on node should make it active/selected

**Comment by keip** [comment]
fixed in d9b5d2cb63

**Comment by chren-de-large** [comment]
still not working
